### PR TITLE
example/kit for fasmg z80 support

### PR DESCRIPTION
**Pull request by stevexyz**
@maziac if you wish you can add this kit / explanations for fasmg and Z80 developments

### CODE REVIEW

**Comment by maziac** [comment]
I'm a little bit reluctant to include this into DeZog.
The thing is: if I add it I also have to give support for it. And I only know little about this assembler or the script.

What I can do instead: I could add a link in DeZog to your fork for everyone interested in fasmg debugging.

**Comment by stevexyz** [comment]
If you want to add a link then might be better the one to the post I did on the sinclair forum posting it: https://sinclairzxworld.com/viewtopic.php?f=6&t=4572

**Comment by maziac** [comment]
OK, fine. I will use that link.

**Comment by maziac** [comment]
Closing the PR.

**Pull request closed without merging**
